// <auto-generated />
using System;
using ATMChallenge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATMChallenge.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATMChallenge.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LastWithdrawal")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "AR12345678",
                            Balance = 10000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastWithdrawal = new DateTime(2026, 1, 30, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "AR87654321",
                            Balance = 25000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastWithdrawal = new DateTime(2026, 1, 29, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "AR11223344",
                            Balance = 5500m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastWithdrawal = new DateTime(2026, 1, 26, 16, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "AR55667788",
                            Balance = 50000m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastWithdrawal = new DateTime(2026, 1, 31, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "AR99887766",
                            Balance = 15750m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastWithdrawal = new DateTime(2026, 1, 28, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("FailedPinAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            CardNumber = "4000000000000001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "$2a$11$TyFAoaAeToGuenFFXqShVOrPc1rYjodYKm58dF6TlRUz8lEu5CA5a"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            CardNumber = "4000000000000002",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "$2a$11$LUCtFqUXof3W7HuPJZcE2uLwzfxKijgFvSoF3SBNF8wypQNCfBjn."
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            CardNumber = "4000000000000003",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "$2a$11$/d7bbpmyYubWmXhVmAoJjuq6zKYd.VOpxUpxBMAcsiQHMA81bHJgq"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            CardNumber = "4000000000000004",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "$2a$11$Z3d5Id2MUipQUH7vDRqrD.NZArJuMUaSo2F2cHAI1Kj6OdQM2nYB2"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            CardNumber = "4000000000000005",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FailedPinAttempts = 0,
                            IsBlocked = false,
                            PinHash = "$2a$11$Lug9xGuT./EImIoBuw2R3eveCjI3PIZCDOyDrSwidDsdBT1NGTTli"
                        });
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Operations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 500m,
                            CreatedAt = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            Amount = 1000m,
                            CreatedAt = new DateTime(2026, 1, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 1,
                            Amount = 250m,
                            CreatedAt = new DateTime(2026, 1, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 1,
                            Amount = 750m,
                            CreatedAt = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 1,
                            Amount = 300m,
                            CreatedAt = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 1,
                            Amount = 1500m,
                            CreatedAt = new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Amount = 200m,
                            CreatedAt = new DateTime(2026, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 14, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            AccountId = 1,
                            Amount = 800m,
                            CreatedAt = new DateTime(2026, 1, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 16, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            AccountId = 1,
                            Amount = 450m,
                            CreatedAt = new DateTime(2026, 1, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 18, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            AccountId = 1,
                            Amount = 1200m,
                            CreatedAt = new DateTime(2026, 1, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            AccountId = 1,
                            Amount = 350m,
                            CreatedAt = new DateTime(2026, 1, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 22, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            AccountId = 1,
                            Amount = 600m,
                            CreatedAt = new DateTime(2026, 1, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 24, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            AccountId = 1,
                            Amount = 900m,
                            CreatedAt = new DateTime(2026, 1, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 26, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            AccountId = 1,
                            Amount = 400m,
                            CreatedAt = new DateTime(2026, 1, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            AccountId = 1,
                            Amount = 550m,
                            CreatedAt = new DateTime(2026, 1, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000001",
                            Timestamp = new DateTime(2026, 1, 30, 10, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            AccountId = 2,
                            Amount = 2000m,
                            CreatedAt = new DateTime(2026, 1, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            AccountId = 2,
                            Amount = 1500m,
                            CreatedAt = new DateTime(2026, 1, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            AccountId = 2,
                            Amount = 3000m,
                            CreatedAt = new DateTime(2026, 1, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            AccountId = 2,
                            Amount = 500m,
                            CreatedAt = new DateTime(2026, 1, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 9, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            AccountId = 2,
                            Amount = 2500m,
                            CreatedAt = new DateTime(2026, 1, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 11, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            AccountId = 2,
                            Amount = 1000m,
                            CreatedAt = new DateTime(2026, 1, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 13, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            AccountId = 2,
                            Amount = 1800m,
                            CreatedAt = new DateTime(2026, 1, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            AccountId = 2,
                            Amount = 700m,
                            CreatedAt = new DateTime(2026, 1, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 17, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            AccountId = 2,
                            Amount = 2200m,
                            CreatedAt = new DateTime(2026, 1, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 19, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            AccountId = 2,
                            Amount = 1300m,
                            CreatedAt = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 23, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            AccountId = 2,
                            Amount = 900m,
                            CreatedAt = new DateTime(2026, 1, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 27, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            AccountId = 2,
                            Amount = 1100m,
                            CreatedAt = new DateTime(2026, 1, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000002",
                            Timestamp = new DateTime(2026, 1, 29, 14, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            AccountId = 3,
                            Amount = 300m,
                            CreatedAt = new DateTime(2026, 1, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            AccountId = 3,
                            Amount = 450m,
                            CreatedAt = new DateTime(2026, 1, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            AccountId = 3,
                            Amount = 600m,
                            CreatedAt = new DateTime(2026, 1, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 10, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            AccountId = 3,
                            Amount = 200m,
                            CreatedAt = new DateTime(2026, 1, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            AccountId = 3,
                            Amount = 800m,
                            CreatedAt = new DateTime(2026, 1, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 16, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            AccountId = 3,
                            Amount = 350m,
                            CreatedAt = new DateTime(2026, 1, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            AccountId = 3,
                            Amount = 500m,
                            CreatedAt = new DateTime(2026, 1, 23, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 23, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            AccountId = 3,
                            Amount = 400m,
                            CreatedAt = new DateTime(2026, 1, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000003",
                            Timestamp = new DateTime(2026, 1, 26, 16, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            AccountId = 4,
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            AccountId = 4,
                            Amount = 3500m,
                            CreatedAt = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            AccountId = 4,
                            Amount = 4200m,
                            CreatedAt = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 9, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            AccountId = 4,
                            Amount = 2800m,
                            CreatedAt = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 12, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            AccountId = 4,
                            Amount = 6000m,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            AccountId = 4,
                            Amount = 1500m,
                            CreatedAt = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            AccountId = 4,
                            Amount = 3000m,
                            CreatedAt = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            AccountId = 4,
                            Amount = 4500m,
                            CreatedAt = new DateTime(2026, 1, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            AccountId = 4,
                            Amount = 2000m,
                            CreatedAt = new DateTime(2026, 1, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            AccountId = 4,
                            Amount = 3800m,
                            CreatedAt = new DateTime(2026, 1, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000004",
                            Timestamp = new DateTime(2026, 1, 31, 9, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            AccountId = 5,
                            Amount = 1000m,
                            CreatedAt = new DateTime(2026, 1, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            AccountId = 5,
                            Amount = 850m,
                            CreatedAt = new DateTime(2026, 1, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 9, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            AccountId = 5,
                            Amount = 1200m,
                            CreatedAt = new DateTime(2026, 1, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 13, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            AccountId = 5,
                            Amount = 950m,
                            CreatedAt = new DateTime(2026, 1, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 17, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            AccountId = 5,
                            Amount = 1100m,
                            CreatedAt = new DateTime(2026, 1, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 51,
                            AccountId = 5,
                            Amount = 750m,
                            CreatedAt = new DateTime(2026, 1, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 25, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 52,
                            AccountId = 5,
                            Amount = 900m,
                            CreatedAt = new DateTime(2026, 1, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "4000000000000005",
                            Timestamp = new DateTime(2026, 1, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        });
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            FullName = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            FullName = "María García"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            FullName = "Carlos López"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            FullName = "Ana Martínez"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            FullName = "Pedro Rodríguez"
                        });
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.Card", b =>
                {
                    b.HasOne("ATMChallenge.Domain.Entities.Account", "Account")
                        .WithMany("Cards")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.Operation", b =>
                {
                    b.HasOne("ATMChallenge.Domain.Entities.Account", "Account")
                        .WithMany("Operations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.User", b =>
                {
                    b.HasOne("ATMChallenge.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ATMChallenge.Domain.Entities.Account", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Operations");
                });
#pragma warning restore 612, 618
        }
    }
}
