<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a5c8b1c1-8ddb-4be4-9da6-4e157e68ca25</UserSecretsId>
    <DockerDefaultTargetOS>Windows</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ATMChallenge.Application\ATMChallenge.Application.csproj" />
    <ProjectReference Include="..\ATMChallenge.Infrastructure\ATMChallenge.Infrastructure.csproj" />
    <ProjectReference Include="..\ATMChallenge.Domain\ATMChallenge.Domain.csproj" />
  </ItemGroup>

</Project>
